const ConteoGTerritorios = {
    "jsonarray": [
         {
            "id_ti": "TQ",
            "territorio": "Territorio Indígena del Río Tiquié",
            "numero_comunidades": "11",
            "numero_personas": 787,
            "numero_mujeres":376,
            "numero_hombres":411,
            "numero_personas_residentes": "669",
            "numero_personas_no_residentes": "118",
            "numero_familias": "166",
            "numero_clanes": "0",
            "numero_pueblos": "20",
            "numero_sabedores": "56",
            "numero_chagras": "381",
            "numero_chagras_familiares": "380",
            "numero_chagras_comunitarias": "1",
            "numero_malocas": "14",
            "numero_malocas_tradicionales": "12",
            "numero_malocas_escolares": "1",
            "numero_malocas_rituales": "0",
            "numero_malocas_comunitarias": "4",
            "numero_malocas_dentro_comunidad": "14",
            "numero_malocas_fuera_de_comunidad": "0"
    }, {
            "id_ti": "YA",
            "territorio": "Territorio Indígena de Yaigojé Apaporis",
            "numero_comunidades": "22",
            "numero_personas": 1925,
            "numero_mujeres":911,
            "numero_hombres": 1014,
            "numero_personas_residentes": "1735",
            "numero_personas_no_residentes": "190",
            "numero_familias": "438",
            "numero_clanes": "44",
            "numero_pueblos": "35",
            "numero_sabedores": "71",
            "numero_chagras": "920",
            "numero_chagras_familiares": "920",
            "numero_chagras_comunitarias": "0",
            "numero_malocas": "48",
            "numero_malocas_tradicionales": "35",
            "numero_malocas_escolares": "1",
            "numero_malocas_rituales": "2",
            "numero_malocas_comunitarias": "10",
            "numero_malocas_dentro_comunidad": "44",
            "numero_malocas_fuera_de_comunidad": "3"
    }, {
            "id_ti": "MP",
            "territorio": "Territorio Indígena Mirití Paraná",
            "numero_comunidades": "13",
            "numero_personas": 1083,
            "numero_mujeres":517,
            "numero_hombres":566,
            "numero_personas_residentes": "973",
            "numero_personas_no_residentes": "110",
            "numero_familias": "240",
            "numero_clanes": "0",
            "numero_pueblos": "21",
            "numero_sabedores": "106",
            "numero_chagras": "571",
            "numero_chagras_familiares": "563",
            "numero_chagras_comunitarias": "8",
            "numero_malocas": "32",
            "numero_malocas_tradicionales": "32",
            "numero_malocas_escolares": "0",
            "numero_malocas_rituales": "0",
            "numero_malocas_comunitarias": "0",
            "numero_malocas_dentro_comunidad": "28",
            "numero_malocas_fuera_de_comunidad": "4"
    },  {
            "id_ti": "PP",
            "territorio": "Territorio Indígena del Pirá Paraná",
            "numero_comunidades": "17",
            "numero_personas": 2246,
            "numero_mujeres":1073,
            "numero_hombres":1173,
            "numero_personas_residentes": "1653",
            "numero_personas_no_residentes": "229",
            "numero_familias": "418",
            "numero_clanes": "4",
            "numero_pueblos": "26",
            "numero_sabedores": "96",
            "numero_chagras": "1049",
            "numero_chagras_familiares": "1048",
            "numero_chagras_comunitarias": "1",
            "numero_malocas": "52",
            "numero_malocas_tradicionales": "40",
            "numero_malocas_escolares": "2",
            "numero_malocas_rituales": "0",
            "numero_malocas_comunitarias": "13",
            "numero_malocas_dentro_comunidad": "32",
            "numero_malocas_fuera_de_comunidad": "14"
    }] };